- name: Configure iptables rule on FW
  hosts: localhost
  become: true
  vars:
    log_prefix: "IPTABLES-DROPPED: "
  tasks:

    - name: Del rule to accept all established connection or is RELATED to an established connection
      command: ip netns exec {{vm_name}} iptables -D FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

    - name: Add iptables rule for FORWARD chain
      command: >
        ip netns exec {{ vm_name }} iptables
        -t filter
        -s "{{ src_ip }}"
        -d "{{ dest_ip }}"
        -p "{{ protocol }}"
        --sport "{{ src_port }}"
        --dport "{{ dest_port }}"
        -m conntrack --ctstate NEW,RELATED,ESTABLISHED
        -m limit --limit "{{ threshold }}/second"
        -j "{{ policy_action }}"
        -I FORWARD 1
      when: protocol != "icmp"

    - name: Add iptables rule for ICMP in FORWARD chain
      command: >
        ip netns exec {{ vm_name }} iptables
        -t filter
        -s "{{ src_ip }}"
        -d "{{ dest_ip }}"
        -p icmp
        -m conntrack --ctstate NEW,RELATED,ESTABLISHED
        -m limit --limit "{{ threshold }}/second"
        -j ACCEPT
        -I FORWARD 1
      when: protocol == "icmp"

    - name: Add iptables rule to log dropped packets
      command: >
        ip netns exec {{ vm_name }} iptables
        -t filter
        -s "{{ src_ip }}"
        -d "{{ dest_ip }}"
        -p "{{ protocol }}"
        --sport "{{ src_port }}"
        --dport "{{ dest_port }}"
        -j LOG
        --log-prefix "{{ log_prefix }}"
        --log-level warning
        -I FORWARD 2
      when: protocol != "icmp"

    - name: Add iptables rule to log dropped packets
      command: >
        ip netns exec {{ vm_name }} iptables
        -t filter
        -s "{{ src_ip }}"
        -d "{{ dest_ip }}"
        -p icmp
        -j LOG
        --log-prefix "{{ log_prefix }}"
        --log-level warning
        -I FORWARD 2
      when: protocol == "icmp"

    - name: Add iptables rule for drop exceeded FORWARD chain
      command: >
        ip netns exec {{ vm_name }} iptables
        -t filter
        -s "{{ src_ip }}"
        -d "{{ dest_ip }}"
        -p "{{ protocol }}"
        --sport "{{ src_port }}"
        --dport "{{ dest_port }}"
        -j DROP
        -I FORWARD 3
      when: protocol != "icmp"

    - name: Add iptables rule for drop exceeded ICMP in FORWARD chain
      command: >
        ip netns exec {{ vm_name }} iptables
        -t filter
        -s "{{ src_ip }}"
        -d "{{ dest_ip }}"
        -p icmp
        -j DROP
        -I FORWARD 3
      when: protocol == "icmp"

   - name: Add rule to accept all established connection or is RELATED to an established connection
      command: ip netns exec {{vm_name}} iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT