---
- name: Attach bridge to a container using a veth pair
  hosts: localhost
  become: true
  vars:
    vm_net: "mgmt"
    namespace_ID: "{{ last_mac }}"
    
  tasks:
    

    - name: Create veth pair
      command: ip link add {{ vm_net }}_{{ vm_name }}_0 type veth peer name {{ vm_net }}_{{ vm_name }}_1
    
    - name: Add veth pair to OVS bridge
      command: ovs-vsctl add-port {{ vm_net }} {{ vm_net }}_{{ vm_name }}_0
   
    - name: Move veth pair to namespace
      command: ip link set {{ vm_net }}_{{ vm_name }}_1 netns {{ vm_name }}
    
    - name: assign mac address for veth_t
      command: ip netns exec {{ vm_name }} ip link set dev {{ vm_net }}_{{ vm_name }}_1  address 52:54:00:10:09:{{ namespace_ID }}
    
    - name: assign as DHClient for veth_t
      command: ip netns exec {{ vm_name }} dhclient {{ vm_net }}_{{ vm_name }}_1

    - name: Set veth pair up
      command: ip link set {{ vm_net }}_{{ vm_name }}_0 up

    - name: Set veth pair up in namespace
      command: ip netns exec {{ vm_name }} ip link set {{ vm_net }}_{{ vm_name }}_1 up
