---
- name: Create OVS bridge and attach it to a namespace using a veth pair
  hosts: localhost
  become: true
  vars:
    ovs_bridge_name: c1br
    namespace_name: c2
    veth_pair_name: c2veth
    ip_address_ns: 192.168.1.3
  tasks:
    - name: Create OVS bridge
      shell: sudo ovs-vsctl add-br {{ ovs_bridge_name }}
	  
	  
    - name: Create veth pair
      shell: sudo ip link add {{ veth_pair_name }} type veth peer name {{ veth_pair_name }}_ns
	  
	  - name: Add veth pair to OVS bridge
      shell: sudo ovs-vsctl add-port {{ ovs_bridge_name }} {{ veth_pair_name }}
   

    - name: Move veth pair to namespace
      shell: sudo ip link set {{ veth_pair_name }}_ns netns {{ namespace_name }}
    

    - name: Add IP address to veth pair in namespace
      shell: sudo ip netns exec {{ namespace_name }} ip addr add {{ ip_address_ns }}/24 dev {{ veth_pair_name }}_ns

    - name: Set veth pair up
      shell: sudo ip link set {{ veth_pair_name }} up

    - name: Set veth pair up in namespace
      shell: sudo ip netns exec {{ namespace_name }} ip link set {{ veth_pair_name }}_ns up
