---
- name: Create docker container and expose namespace
  hosts: localhost
  become: true
  vars:
    image_name: ubuntuimage
    vm_name: "{{ namespace_tenant }}{{ hostname }}" 
  tasks:
    - name: Creating container
      docker_container:
        image: "{{ image_name }}"
        name: "{{vm_name}}"
        state: started
        hostname: "{{vm_name}}"
        privileged: yes
        interactive: yes
        tty: yes
        purge_networks: yes
   
    - name: Get container PID
      shell: docker inspect {{vm_name}} | grep '"Pid"' | awk '{ print $2 }' | sed 's/,.*//'
      register: container_pid

    - name: Create net namespace
      shell: ln -sf /proc/{{ container_pid.stdout }}/ns/net /var/run/netns/{{vm_name}}



    - name: Start SSH service
      shell: docker exec {{vm_name}} service ssh start
