- name: Configure iptables rule on FW
  hosts: localhost
  become: true    
  vars:
    log_prefix: "IPTABLES-DROPPED: "
  tasks:
    - name: Del iptables rule for FORWARD chain
      command: >
        ip netns exec {{ vm_name }} iptables
        -t filter
        -D FORWARD
        -s "{{ src_ip }}"
        -d "{{ dest_ip }}"
        -p "{{ protocol }}"
        --sport "{{ src_port }}"
        --dport "{{ dest_port }}"
        -m limit --limit "{{ threshold }}/second"
        -j "{{ policy_action }}"
      when: protocol != "icmp"

    - name: Del iptables rule to log dropped packets
      command: >
        ip netns exec {{ vm_name }} iptables
        -t filter
        -D FORWARD
        -s "{{ src_ip }}"
        -d "{{ dest_ip }}"
        -p "{{ protocol }}"
        --sport "{{ src_port }}"
        --dport "{{ dest_port }}"
        -m limit --limit "{{ threshold }}/second"
        -j LOG
        --log-prefix "{{ log_prefix }}"
        --log-level warning
      when: protocol != "icmp"
