- name: Configure Initial setup on FW
  hosts: localhost
  become: true    
  vars:
    vm_net_in: "{{ namespace_tenant }}_FwI_BR"
    vm_net_out: "{{ namespace_tenant }}_FwE_BR"
    vm_name: "{{ namespace_tenant }}{{ hostname }}"
    IN_int: {{ vm_net_in }}_{{ vm_name[-3:] }}_1
    OUT_int: {{ vm_net_out }}_{{ vm_name[-3:] }}_1
    OUT_gw: "10.8.8.1"
    IN_gw: "10.7.7.1"
  tasks:

    - name: Add iptables rule for NAT public traffic
      command: ip netns exec {{vm_name}} iptables -t nat -I POSTROUTING 1 -o {{ OUT_int }} -j MASQUERADE
      
    

    - name: Add rule to accept all established connection or is related to an established connection
      command: ip netns exec {{vm_name}} iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

    - name: Add iptables rule to drop all invalid packets
      command: ip netns exec {{vm_name}} iptables -A INPUT -m conntrack --ctstate INVALID -j DROP

    - name: Add rule to accept all established connection or is related to an established connection
      command: ip netns exec {{vm_name}} iptables -I FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

    - name: Add iptables rule to drop all invalid packets
      command: ip netns exec {{vm_name}} iptables -I FORWARD -m conntrack --ctstate INVALID -j DROP

    - name: Add rule to default deny  
      command: ip netns exec {{vm_name}} iptables -P FORWARD DROP

    - name: Add route for the internal 10.0.0.0/8 network
      command: ip netns exec {{vm_name}} ip route add 10.0.0.0/8 via {{ IN_gw }} dev {{ IN_int }}

    - name: Add route for the internal 172.16.0.0/12 network
      command: ip netns exec {{vm_name}} ip route add 172.16.0.0/12 via {{ IN_gw }} dev {{ IN_int }}

    - name: Add route for the internal 192.168.0.0/16 network
      command: ip netns exec {{vm_name}} ip route add 192.168.0.0/16 via {{ IN_gw }} dev {{ IN_int }}
      
    - name: Add default route towards external interface
      command: ip netns exec {{vm_name}} ip route add default via {{ OUT_gw }} dev {{ OUT_int }}
