---
- name: Configure VRRP
  hosts: localhost

  vars:
    src_dir: "/home/csc792/FwaaS-VPC-Containerzed/south_bound/templates"
    virtual_ip: 10.7.7.100
    vm_net_in: "{{ namespace_tenant }}_FwI"
    vm_name: "{{ namespace_tenant }}{{ hostname }}"
    vrrp_interface: "{{ vm_net_in }}_{{ vm_name[-3:] }}_1"
    vrrp_loc: "{{src_dir}}/keepalived.conf.j2" 

  tasks:
    - name: Configure keepalived
      template:
        src: "{{src_dir}}/keepalived.conf.j2"
        dest: "{{src_dir}}/keepalived.conf"
        mode: "0644"
      register: template_result

    - name: Copy keepalived
      command: docker cp {{template_result.dest}} {{vm_name}}:/etc/keepalived/

    - name: Run keepalived service
      command: docker exec {{vm_name}} service keepalived start

    - name: Remove keepalived file
      file:
        path: "{{ template_result.dest }}"
        state: absent


